export { default as CS } from "@/services/CharacterService"
export { default as VS } from "@/services/VehicleService"
export { default as SS } from "@/services/SharedService"
export { default as DS } from "@/services/DiceService"
export { default as FS } from "@/services/FightService"
export { default as CES } from "@/services/CharacterEffectService"
