import type {
  VehicleActionValues,
  ActionValues,
  Faction,
  Person,
  Vehicle,
  Fight,
  User,
  Effect,
  Toast,
  Campaign,
  CharacterEffect,
  Schtick,
  Advancement,
  Juncture,
  Site,
  Party,
  Weapon,
  PaginationMeta,
  Location,
  Swerve,
} from "@/types"

export const defaultFaction: Faction = {
  entity_class: "Faction",
  id: "",
  name: "",
  description: "",
  characters: [],
  vehicles: [],
  active: true,
  parties: [],
  sites: [],
  junctures: [],
  character_ids: [],
  vehicle_ids: [],
  party_ids: [],
  site_ids: [],
  juncture_ids: [],
  image_url: "",
  created_at: "",
  updated_at: "",
}

export const defaultCharacter: Person = {
  entity_class: "Person",
  id: "",
  name: "",
  category: "character",
  active: true,
  current_shot: 0,
  impairments: 0,
  color: "",
  faction_id: null,
  faction: defaultFaction,
  action_values: {
    Archetype: "",
    Guns: 0,
    "Martial Arts": 0,
    Sorcery: 0,
    Scroungetech: 0,
    Genome: 0,
    Creature: 0,
    Defense: 0,
    Toughness: 0,
    Speed: 0,
    Fortune: 0,
    "Max Fortune": 0,
    FortuneType: "Fortune",
    MainAttack: "Guns",
    SecondaryAttack: null,
    Wounds: 0,
    Type: "Featured Foe",
    Vehicle: false,
    "Marks of Death": 0,
    Damage: 0,
  } as ActionValues,
  description: {
    Nicknames: "",
    Age: "",
    Height: "",
    Weight: "",
    "Hair Color": "",
    "Eye Color": "",
    "Style of Dress": "",
    Appearance: "",
    Background: "",
    "Melodramatic Hook": "",
  },
  schticks: [],
  skills: {},
  advancements: [],
  sites: [],
  weapons: [],
  count: 0,
  shot_id: "",
  image_url: "",
  task: false,
  notion_page_id: null,
  wealth: "Poor",
  juncture_id: null,
  juncture: null,
  user_id: "",
  created_at: "",
  updated_at: "",
} as Person

export const defaultVehicle: Vehicle = {
  entity_class: "Vehicle",
  id: "",
  name: "",
  active: true,
  category: "vehicle",
  current_shot: "",
  impairments: 0,
  color: "",
  faction_id: null,
  faction: defaultFaction,
  action_values: {
    Acceleration: 0,
    Handling: 0,
    Squeal: 0,
    Frame: 0,
    Crunch: 0,
    "Chase Points": 0,
    "Condition Points": 0,
    Pursuer: "true",
    Position: "far",
    Type: "Featured Foe",
  } as VehicleActionValues,
  description: {
    Nicknames: "",
    Age: "",
    Height: "",
    Weight: "",
    "Hair Color": "",
    "Eye Color": "",
    "Style of Dress": "",
    Appearance: "",
    Background: "",
    "Melodramatic Hook": "",
  },
  schticks: [],
  skills: {},
  advancements: [],
  sites: [],
  weapons: [],
  count: 0,
  shot_id: "",
  driver: defaultCharacter,
  image_url: "",
  task: false,
  notion_page_id: null,
  wealth: "",
  juncture_id: null,
  juncture: null,
  created_at: "",
  updated_at: "",
  user_id: "",
} as Vehicle

export const defaultFight: Fight = {
  entity_class: "Fight",
  id: "",
  name: "",
  description: "",
  active: true,
  sequence: 0,
  effects: [],
  actors: [],
  characters: [],
  shot_order: [],
  character_effects: {},
  vehicle_effects: {},
  image_url: "",
  created_at: "",
  updated_at: "",
}

export const defaultUser: User = {
  entity_class: "User",
  id: "",
  email: "",
  name: "",
  image_url: "",
  created_at: "",
  updated_at: "",
}

export const defaultEffect: Effect = {
  id: "",
  name: "",
  description: "",
  severity: "error",
  start_sequence: 1,
  end_sequence: 2,
  start_shot: 15,
  end_shot: 15,
}

export const defaultToast: Toast = {
  open: false,
  message: "",
  severity: "success",
}

export const defaultCampaign: Campaign = {
  entity_class: "Campaign",
  id: "",
  name: "",
  description: "",
  gamemaster: defaultUser,
  players: [],
  player_ids: [],
  invitations: [],
  image_url: "",
  created_at: "",
  updated_at: "",
}

export const defaultCharacterEffect: CharacterEffect = {
  id: "",
  name: "",
  description: "",
  severity: "info",
  character_id: "",
  shot_id: "",
  vehicle_id: "",
}

export const defaultSchtick: Schtick = {
  entity_class: "Schtick",
  id: "",
  name: "",
  description: "",
  campaign_id: "",
  category: "",
  path: "",
  schtick_id: "",
  prerequisite: {
    id: "",
    name: "",
  },
  color: "",
  image_url: "",
  created_at: "",
  updated_at: "",
}

export const defaultAdvancement: Advancement = {
  description: "",
}

export const defaultJuncture: Juncture = {
  entity_class: "Juncture",
  id: "",
  name: "",
  description: "",
  faction: null,
  faction_id: null,
  active: true,
  image_url: "",
  characters: [],
  created_at: "",
  updated_at: "",
}

export const defaultSite: Site = {
  entity_class: "Site",
  id: "",
  name: "",
  description: "",
  faction: null,
  faction_id: null,
  secret: false,
  image_url: "",
  characters: [],
  created_at: "",
  updated_at: "",
}

export const defaultParty: Party = {
  entity_class: "Party",
  id: "",
  name: "",
  description: "",
  faction: null,
  faction_id: null,
  characters: [],
  vehicles: [],
  character_ids: [],
  vehicle_ids: [],
  secret: false,
  image_url: "",
  created_at: "",
  updated_at: "",
}

export const defaultWeapon: Weapon = {
  entity_class: "Weapon",
  id: "",
  name: "",
  description: "",
  damage: 7,
  concealment: 0,
  reload_value: 0,
  juncture: "",
  category: "",
  mook_bonus: 0,
  kachunk: false,
  image_url: "",
  created_at: "",
  updated_at: "",
}

export const defaultPaginationMeta: PaginationMeta = {
  current_page: 1,
  next_page: null,
  prev_page: null,
  total_pages: 1,
  total_count: 1,
}

export const defaultLocation: Location = {
  name: "",
}

export const defaultSwerve: Swerve = {
  result: 0,
  positiveRolls: [],
  negativeRolls: [],
  positive: 0,
  negative: 0,
  boxcars: false,
}
